-- BCSO Portal — Migration 3 (Cloudflare D1 / SQLite)
--
-- NOT NEEDED — skip this file.
--
-- This originally added a separate "wording" column to Deputy Movement
-- templates. That approach was replaced: the existing "Role ID(s) to
-- ping" field on a template now accepts a mix of numeric Discord role
-- IDs (pinged) AND plain words/phrases (included as literal text) in
-- the same comma-separated list, so no extra column is needed.
--
-- If you already ran this file before reading this note, no harm done
-- — it just added one unused column (movement_templates.wording) that
-- nothing reads or writes anymore. If you haven't run it, don't bother.
